### ISSUE TITLE
p4-validate needs python-yaml and p4-graphs needs dot

### ISSUE THREAD

**Issue by jeromesun14** [p4lang/p4-hlir#8]
# README do not tell p4-validate and p4-graphs dependency.

p4-validate needs python-yaml and p4-graphs needs dot, but README do not tell us the dependency of these tools.

The following log use p4 tutorials/examples/counter/p4src/counter.p4 as example.
## p4-validate needs python-yaml

```
Traceback (most recent call last):
  File "/usr/local/bin/p4-validate", line 5, in <module>
    pkg_resources.run_script('p4-hlir==0.9.29', 'p4-validate')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/p4_hlir-0.9.29-py2.7.egg/EGG-INFO/scripts/p4-validate", line 19, in <module>
    import yaml
ImportError: No module named yaml
```

After install `python-yaml`, p4-validate works fine.

```
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ sudo apt-get install python-yaml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libyaml-0-2
The following NEW packages will be installed:
  libyaml-0-2 python-yaml
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 150 kB of archives.
After this operation, 640 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main libyaml-0-2 amd64 0.1.4-3ubuntu3.1 [48.1 kB]
Get:2 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main python-yaml amd64 3.10-4ubuntu0.1 [102 kB]
Fetched 150 kB in 0s (167 kB/s)      
Selecting previously unselected package libyaml-0-2:amd64.
(Reading database ... 176125 files and directories currently installed.)
Preparing to unpack .../libyaml-0-2_0.1.4-3ubuntu3.1_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.1.4-3ubuntu3.1) ...
Selecting previously unselected package python-yaml.
Preparing to unpack .../python-yaml_3.10-4ubuntu0.1_amd64.deb ...
Unpacking python-yaml (3.10-4ubuntu0.1) ...
Setting up libyaml-0-2:amd64 (0.1.4-3ubuntu3.1) ...
Setting up python-yaml (3.10-4ubuntu0.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ 
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ 
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ 
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ p4-validate counter.p4 
WARNING: No error rule is defined for exclusive state 'pragma'
WARNING: Token 'DIVIDE' defined, but not used
WARNING: Token 'PPHASH' defined, but not used
WARNING: Token 'MOD' defined, but not used
WARNING: There are 3 unused tokens
parsing successful
Semantic warning: header instance 'meta' is not reachable and will be removed
Semantic warning: action '_drop' is not reachable and will be removed
Semantic warning: header type 'meta_t' is not reachable and will be removed
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$
```
## p4-graphs needs dot

```
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ p4-graphs counter.p4 
WARNING: No error rule is defined for exclusive state 'pragma'
WARNING: Token 'DIVIDE' defined, but not used
WARNING: Token 'PPHASH' defined, but not used
WARNING: Token 'MOD' defined, but not used
WARNING: There are 3 unused tokens
parsing successful
Semantic warning: header instance 'meta' is not reachable and will be removed
Semantic warning: action '_drop' is not reachable and will be removed
Semantic warning: header type 'meta_t' is not reachable and will be removed
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
Generating files in directory /home/sunnogo/research/p4/tutorials/examples/counter/p4src
Generating eps
Traceback (most recent call last):
  File "/usr/local/bin/p4-graphs", line 5, in <module>
    pkg_resources.run_script('p4-hlir==0.9.29', 'p4-graphs')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/p4_hlir-0.9.29-py2.7.egg/EGG-INFO/scripts/p4-graphs", line 112, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/p4_hlir-0.9.29-py2.7.egg/EGG-INFO/scripts/p4-graphs", line 102, in main
    dot.export_parse_graph(h, basename, gen_dir)
  File "/usr/local/lib/python2.7/dist-packages/p4_hlir-0.9.29-py2.7.egg/p4_hlir/graphs/dot.py", line 142, in export_parse_graph
    generate_graph_eps(filename_dot, filename_eps)
  File "/usr/local/lib/python2.7/dist-packages/p4_hlir-0.9.29-py2.7.egg/p4_hlir/graphs/dot.py", line 119, in generate_graph_eps
    subprocess.check_call(["dot", "-Teps", dot], stdout = epsf)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

After install `graphviz`, p4-graphs works fine.

```
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ sudo apt-get install graphviz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libcdt5 libcgraph6 libgvc6 libgvpr2 libpathplan4
Suggested packages:
  graphviz-doc
The following NEW packages will be installed:
  graphviz libcdt5 libcgraph6 libgvc6 libgvpr2 libpathplan4
0 upgraded, 6 newly installed, 0 to remove and 5 not upgraded.
Need to get 1,300 kB of archives.
After this operation, 4,575 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main libcdt5 amd64 2.36.0-0ubuntu3.1 [23.3 kB]
Get:2 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main libcgraph6 amd64 2.36.0-0ubuntu3.1 [44.1 kB]
Get:3 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main libpathplan4 amd64 2.36.0-0ubuntu3.1 [26.3 kB]
Get:4 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main libgvc6 amd64 2.36.0-0ubuntu3.1 [576 kB]
Get:5 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main libgvpr2 amd64 2.36.0-0ubuntu3.1 [169 kB]
Get:6 http://mirrors.yun-idc.com/ubuntu/ trusty-updates/main graphviz amd64 2.36.0-0ubuntu3.1 [461 kB]
Fetched 1,300 kB in 3s (362 kB/s) 
Selecting previously unselected package libcdt5.
(Reading database ... 176162 files and directories currently installed.)
Preparing to unpack .../libcdt5_2.36.0-0ubuntu3.1_amd64.deb ...
Unpacking libcdt5 (2.36.0-0ubuntu3.1) ...
Selecting previously unselected package libcgraph6.
Preparing to unpack .../libcgraph6_2.36.0-0ubuntu3.1_amd64.deb ...
Unpacking libcgraph6 (2.36.0-0ubuntu3.1) ...
Selecting previously unselected package libpathplan4.
Preparing to unpack .../libpathplan4_2.36.0-0ubuntu3.1_amd64.deb ...
Unpacking libpathplan4 (2.36.0-0ubuntu3.1) ...
Selecting previously unselected package libgvc6.
Preparing to unpack .../libgvc6_2.36.0-0ubuntu3.1_amd64.deb ...
Unpacking libgvc6 (2.36.0-0ubuntu3.1) ...
Selecting previously unselected package libgvpr2.
Preparing to unpack .../libgvpr2_2.36.0-0ubuntu3.1_amd64.deb ...
Unpacking libgvpr2 (2.36.0-0ubuntu3.1) ...
Selecting previously unselected package graphviz.
Preparing to unpack .../graphviz_2.36.0-0ubuntu3.1_amd64.deb ...
Unpacking graphviz (2.36.0-0ubuntu3.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libcdt5 (2.36.0-0ubuntu3.1) ...
Setting up libcgraph6 (2.36.0-0ubuntu3.1) ...
Setting up libpathplan4 (2.36.0-0ubuntu3.1) ...
Setting up libgvc6 (2.36.0-0ubuntu3.1) ...
Setting up libgvpr2 (2.36.0-0ubuntu3.1) ...
Setting up graphviz (2.36.0-0ubuntu3.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ p4-graphs counter.p4 
WARNING: No error rule is defined for exclusive state 'pragma'
WARNING: Token 'DIVIDE' defined, but not used
WARNING: Token 'PPHASH' defined, but not used
WARNING: Token 'MOD' defined, but not used
WARNING: There are 3 unused tokens
parsing successful
Semantic warning: header instance 'meta' is not reachable and will be removed
Semantic warning: action '_drop' is not reachable and will be removed
Semantic warning: header type 'meta_t' is not reachable and will be removed
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
Generating files in directory /home/sunnogo/research/p4/tutorials/examples/counter/p4src

TABLE DEPENDENCIES...

INGRESS PIPELINE
['m_table']
pipeline ingress requires at least 1 stages

EGRESS PIPELINE
Egress pipeline is empty

sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ ls
counter.ingress.tables_dep.dot  counter.p4          counter.parser.eps  counter.tables.dot
counter.ingress.tables_dep.png  counter.parser.dot  counter.parser.png  counter.tables.png
sunnogo@sunyongfeng:~/research/p4/tutorials/examples/counter/p4src$ 
```

**Comment by antoninbas** [comment]
Thanks. I added these dependencies to the README with 3a792e54fdb6c366f65eea9b793d23ead5b6afc4
